var keyCodes = [
    {"letter" : "a", "keyCode" : 65},
    {"letter" : "b", "keyCode" : 66},
    {"letter" : "c", "keyCode" : 67},
    {"letter" : "d", "keyCode" : 68},
    {"letter" : "e", "keyCode" : 69},
    {"letter" : "f", "keyCode" : 70},
    {"letter" : "g", "keyCode" : 71},
    {"letter" : "h", "keyCode" : 72},
    {"letter" : "i", "keyCode" : 73},
    {"letter" : "j", "keyCode" : 74},
    {"letter" : "k", "keyCode" : 75},
    {"letter" : "l", "keyCode" : 76},
    {"letter" : "m", "keyCode" : 77},
    {"letter" : "n", "keyCode" : 78},
    {"letter" : "o", "keyCode" : 79},
    {"letter" : "p", "keyCode" : 80},
    {"letter" : "q", "keyCode" : 81},
    {"letter" : "r", "keyCode" : 82},
    {"letter" : "s", "keyCode" : 83},
    {"letter" : "t", "keyCode" : 84},
    {"letter" : "u", "keyCode" : 85},
    {"letter" : "v", "keyCode" : 86},
    {"letter" : "w", "keyCode" : 87},
    {"letter" : "x", "keyCode" : 88},
    {"letter" : "y", "keyCode" : 89},
    {"letter" : "z", "keyCode" : 90},
];